---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This used to be python-utility-deployment to be better distinguishable, but a suffix of the kind that it is seems redundant.
  name: python-utility
  labels:
    app: python-utility-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-utility-label
  template:
    metadata:
      labels:
        app: python-utility-label
    spec:
      containers:
      - name: python-utility
        image: '{{ .Values.ImagePrefix }}/python-utility:{{ .Chart.AppVersion }}'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
